homework.abilities
homework.base_experience
homework.height
homework.held_items[0].item.url
homework.sprites
homework.stats[0].stat.name
homework.stats[1].stat.name
homework.stats[2].stat.name
homework.stats[3].stat.name
homework.stats[4].stat.name
homework.stats[5].stat.name
homework.types[0].slot
homework.weight
homework.moves[0]